name: Build REST Service

on:
  push:
    branches:
      - master

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew build
      - run: ./gradlew shadowJar
